### ISSUE TITLE
Como melhor traduzir "Mean" e "meannes"  

### ISSUE THREAD

**Issue by everton** [everton/ensaios-paul-graham#1]
Surgiu um dúvida sobre o título do último ensaio: (http://www.paulgraham.com/mean.html)

Durante o ensaio ele usa a palavra "mean" que tem muitas possíveis traduções (indo de "medíocre" a "maldoso") e dado o histórico do author acho que ambos os casos são possíveis.

**Comment by rsnows** [comment]
Por passagens como "It seems quite likely that most successful drug lords are mean" ficou claro que ele vai pelo caminho do "maldoso". Ainda tem que escolher entre as pequenas variações, "maldoso", "mau", "malvado", o que eu vou ver com o progresso do negócio.

**Comment by rsnows** [comment]
Tem uma questão adicional: na maioria dos lugares, "meanness" aparece como "mesquinharia", "mesquinhez", em vez de "maldade". Indica que o conceito em inglês é meio embaralhado entre falta de bondade e falta de generosidade. Ainda assim, acho que a opção da maldade é a que melhor expressa no conjunto geral.

**Comment by everton** [comment]
Especialmente pela citação a traficantes, creio que tens razão sobre
"maldade", mas "mesquinharia" também faz muito sentido em outras partes do
texto.
