### ISSUE TITLE
"like a car spinning its wheels"

### ISSUE THREAD

**Issue by rsnows** [everton/ensaios-paul-graham#2]
Pelo contexto, ficou "como um carro andando em círculos", mas não achei nada referendando essa interpretação.

**Comment by tralara** [comment]
https://www.google.com/search?q=like+a+car+spinning+its+wheels&es_sm=93&tbm=isch&tbo=u&source=univ&sa=X&ei=0lqAVMqlGMKXNouDg9AF&ved=0CFIQ7Ak&biw=1920&bih=939

Em 4 de dezembro de 2014 05:22, rsnows notifications@github.com escreveu:

**Comment by rsnows** [comment]
Hahaha bem bolado. Vou dar uma olhada se tem um termo simples pra essa ideia

**Comment by rsnows** [comment]
"Girar em falso", chama-se.
