### ISSUE TITLE
"recrutting battles"

### ISSUE THREAD

**Issue by rsnows** [everton/ensaios-paul-graham#3]
Tem um termo específico pra isso em português?

**Comment by tralara** [comment]
Não, não existe.
Os americanos são bizarros, gostam de guerra e filmes ruins. Mas eles
valorizam o trabalho, especificamente "makers" de algumas áreas. Na NBA, é
comum um jogador sair de um time e ir pra outro, sem pagar nada. Terminou o
contrato, tem melhor proposta? Vida segue.
É comum um jogador ("executor.") ganhar mais que um treinador ("gerente").
Isso é bem incomum em times brasileiros.
A diferença entre os salários de técnicos
http://www.otherleague.com/contracts/nba-head-coach-contracts-salaries/ e
jogadores http://hoopshype.com/salaries.htm parece ser brutal.

Aqui, não existe isso de brigar por mão de obra. Se ficou acima de um
valor, mesmo o cabra sendo bom, substitui por 10 estagiários.

Resumindo, Será necessário traduzir o termo e dar uma noção cultural para
quem tá lendo do que significa isso, em uma nota de rodapé por exemplo.

2015-01-10 13:30 GMT-03:00 rsnows notifications@github.com:

**Comment by rsnows** [comment]
Eu tenho a impressão de que com todo o contexto do texto, a tradução óbvia "batalhas de recrutamento" já deixa claro do que se trata, não?

**Comment by tralara** [comment]
Ficará na cabeça de quem lê: mas que merda, é só contratar estagiários no
lugar.

Em 11 de janeiro de 2015 15:25, rsnows notifications@github.com escreveu:

**Comment by rsnows** [comment]
Mas esse é O argumento do texto. Que as empresas precisam de gente acima da média. Se o cara ler e não entender isso, pô. Não dá pra fazer o negócio pensando nos analfabetos funcionais. Hahahah

**Comment by tralara** [comment]
Qual é o seu público?
https://twitter.com/jefferraro/status/554357824156102656/photo/1

Em 11 de janeiro de 2015 19:29, rsnows notifications@github.com escreveu:

**Comment by rsnows** [comment]
https://www.youtube.com/watch?v=z-eu6OfSX78

**Comment by rsnows** [comment]
De qualquer forma, agora pensei que o conhecimento da existência de recruiting battles não é necessariamente uma questão de inteligência, então vale uma pequena explicação sim.

Como formatar?

**Comment by tralara** [comment]
Eu acho que é uma questão puramente cultural. nao sei como fazer,
sinceramente.

Em 12 de janeiro de 2015 19:17, rsnows notifications@github.com escreveu:

**Comment by rsnows** [comment]
Inventá-la-ei

**Comment by rsnows** [comment]
Mentira, copiei de um textinho sobre ABNT
