### ISSUE TITLE
Expertise

### ISSUE THREAD

**Issue by rsnows** [everton/ensaios-paul-graham#5]
Em http://www.paulgraham.com/ecw.html, deixei a palavra "expert" do jeito que está. Podia colocar "especialista", mas acho que a palavra original é suficientemente conhecida e expressa melhor a ideia.

No entanto, tem uma ocorrência de "expertise". Também é uma palavra que aparece seguido em textos em português, mas não tanto. De qualquer forma, achei melhor deixar no original também.

**Comment by everton** [comment]
100% manter "expert" e "expertise"...
