### ISSUE TITLE
lame

### ISSUE THREAD

**Issue by rsnows** [everton/ensaios-paul-graham#6]
Jamais pensei que essa palavra fosse precisar ser traduzida. Achei a opção "fraco" e usei ela por todo http://www.paulgraham.com/altair.html. Mas eu imaginei uma opção mais malandra, "tosco". Se pensar nos sentidos literais, não é a mesma coisa, mas me parece exprimir melhor a ideia. Alguém?

**Comment by everton** [comment]
Prefiro "tosco".

**Comment by rsnows** [comment]
Alterado.
