### ISSUE TITLE
Venture capital

### ISSUE THREAD

**Issue by rsnows** [everton/ensaios-paul-graham#8]
Em http://www.paulgraham.com/ronco.html ele usa a abreviação "VC", de "venture capitalist". "Venture capital" é capital de risco, mas 6 sabem se existe uma maneira de se referir à pessoa que aplica esse capital, em sigla ou por extenso mesmo?

**Comment by everton** [comment]
No Brasil é comum usarmos o termo VC mesmo, não traduz-se.

**Comment by everton** [comment]
Veja por exemplo, o portal da Exame sobre o assunto:

> > http://exame.abril.com.br/topicos/venture-capital

Não traduzem
